# Project identification
sonar.projectKey=dadc1007_primitive-clash-frontend
sonar.organization=dadc1007

# Metadata
sonar.projectName=Primitive Clash Frontend
sonar.projectVersion=1.0

# Source code
sonar.sources=src
sonar.tests=src

# Test inclusions (archivos de test)
sonar.test.inclusions=**/__tests__/**/*.test.ts,**/__tests__/**/*.test.tsx,**/__tests__/**/*.spec.ts,**/__tests__/**/*.spec.tsx

# Exclusions (archivos a ignorar en el análisis)
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/public/**,**/*.config.ts,**/*.config.js,**/coverage/**,**/*.d.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/sonar-report.xml

# Source encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=ts
