sonar.projectKey=dadc1007_primitivefronted
sonar.organization=dadc1007

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Primitive Clash Frontend
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=ts

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/public/**,**/*.config.ts,**/*.config.js,**/vite-env.d.ts

# Coverage - Solo LCOV para JavaScript/TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript configuration
sonar.typescript.tsconfigPath=tsconfig.json